name: POC-17

on:
  push:
    branches: [ "master" ]

jobs: 
  build-deploy: 
    runs-on: self-hosted
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: "https://sonarcloud.io"

    steps:

    # Step 1: Checkout the Repo
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up JDK 17 (or 11 depending on your project)
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Step 3: Build with Maven (skip dependency-check)
    - name: Build with Maven
      run: mvn -B clean verify -Ddependency-check.skip=true

    # Step 4: Run SonarQube scan
    - name: Build and analyze with SonarQube
      run: | 
          mvn sonar:sonar \
              -Dsonar.projectKey=banita1985_POC-17GitHub-Action \
              -Dsonar.organization=banita1985 \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

    # Step 5: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # ✅ NEW STEP: Free up space before building Docker image
    - name: Free up space on runner
      run: |
        docker system prune -af || true
        docker volume prune -f || true

    # Step 6: Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/poc-17:1.0 .

  


    # Step 8: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 9: Update kubeconfig for EKS
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name poc-eks-cluster --region ${{ secrets.AWS_REGION }}

    # Step 10: Deploy to EKS
    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yml --validate=false
        kubectl apply -f k8s/service.yml
